name: Mono Client CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install & Tests
        run: |
          npm install
          npm test